name: Auto Deploy to CloudPanel

on:
  push:
    branches:
      - main  # Ubah ke 'master' jika branch Anda bernama master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: 'e-spmii'
          server: '153.92.5.200'
          port: 4096
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './*'
          remote_path: '/home/ikipsiliwangi-e-spmi/htdocs/e-spmi.ikipsiliwangi.ac.id/'